[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "Berkeley Mono"

[colors]
cursor = { text = "#000000", cursor = "#33ff33" }

[colors.normal]
black = '#000000'
red = '#ff8389'
green = '#42be65'
yellow = '#d2a106'
blue = "#33b1ff"
magenta = '#be95ff'
cyan = '#08bdba'
white = '#c6c6c6'

[colors.bright]
black = '#6f6f6f'
red = '#ffb3b8'
green = '#6fdc8c'
yellow = '#f1c21b'
blue = "#82cfff"
magenta = '#d4bbff'
cyan = '#3ddbd9'
white = '#ffffff'

[colors.primary]
background = '#022b30'
foreground = '#c6c6c6'

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0

[mouse]
hide_when_typing = true
