[env]
TERM = "xterm-256color"

[font]
size = 25

[font.normal]
family = "Berkeley Mono"

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0

[mouse]
hide_when_typing = true

[colors.primary]
background = "#000000"
foreground = "#dadada"

[colors.normal]
black = '#000000'
red = '#d7005f'
green = '#00af5f'
yellow = '#d78700'
blue = '#0087d7'
magenta = '#d787d7'
cyan = '#00afaf'
white = '#dadada'

[colors.bright]
black = '#707070'
red = '#ff005f'
green = '#00d75f'
yellow = '#ffaf00'
blue = '#5fafff'
magenta = '#ff87ff'
cyan = '#00d7d7'
white = '#ffffff'
