[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "Berkeley Mono"

[general]
import = ["nvim_light.toml"]


[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0

[mouse]
hide_when_typing = true
