[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "Berkeley Mono"
# family = "Departure Mono"
# family = "IBM Plex Mono"

[general]
import = ["quiet_dark.toml"]
# import = ["green.toml"]
# import = ["amber.toml"]
# import = ["quiet_light.toml"]

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0

[mouse]
hide_when_typing = true
