[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "Berkeley Mono"

[general]
import = ["dark.toml"]

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0

[mouse]
hide_when_typing = true
