[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "Berkeley Mono"


# Colors are taken from vim/neovim built-in quiet theme https://github.com/neovim/neovim/blob/b7e896671500a6e9a0c773bc6bac2d073e588eba/runtime/colors/quiet.vim 
[colors.normal]
black = '#000000'
red = '#d7005f'
green = '#00af5f'
yellow = '#d78700'
blue = '#0087d7'
magenta = '#d787d7'
cyan = '#00afaf'
white = '#dadada'

[colors.bright]
black = '#707070'
red = '#ff005f'
green = '#00d75f'
yellow = '#ffaf00'
blue = '#5fafff'
magenta = '#ff87ff'
cyan = '#00d7d7'
white = '#ffffff'

[colors.primary]
background = '#000000'
foreground = '#dadada'

[colors.selection]
background = '#4f5258'
text = '#e0e2ea'

[window]
decorations = "none"
startup_mode = "Maximized"
# opacity = 0.8

[window.padding]
x = 7
y = 0
