[colors]
cursor = { text = "#000000", cursor = "#33ff33" }

[colors.normal]
black = '#000000'
red = '#fa4d56'
green = '#24a148'
yellow = '#b28600'
blue = "#1192e8"
magenta = '#a56eff'
cyan = '#009d9a'
white = '#c6c6c6'

[colors.bright]
black = '#6f6f6f'
red = '#ff8389'
green = '#42be65'
yellow = '#d2a106'
blue = "#33b1ff"
magenta = '#be95ff'
cyan = '#08bdba'
white = '#ffffff'

[colors.primary]
# background = '#262626'
background = '#161616'
foreground = '#c6c6c6'
