[colors.primary]
foreground = "#87ff87"
background = "#000000"

[colors.normal]
black = '#303030'
red = '#ffa700'
green = '#005f00'
yellow = '#ffd7af'
blue = '#87afff'
magenta = '#ffafaf'
cyan = '#00afaf'
white = '#bcbcbc'

[colors.bright]
black = '#444444'
red = '#ff0000'
green = '#00875f'
yellow = '#ffff00'
blue = '#005fff'
magenta = '#ff00ff'
cyan = '#00ffff'
white = '#ffffff'
