[colors.primary]
background = "#E0E2EA"
foreground = "#14161b"

[colors.normal]
black = "#C4C6CD"
red = "#590008"
green = "#005523"
yellow = "#6b5300"
blue = "#004c63"
magenta = "#470045"
cyan = "#007373"
white = "#2c2e33"

[colors.bright]
black = "#9b9ea4"
red = "#590008"
green = "#005523"
yellow = "#6b5300"
blue = "#004c63"
magenta = "#470045"
cyan = "#007373"
white = "#4f5258"
