[colors.primary]
foreground = "#dadada"
background = "#000000"


[colors.normal]
red = '#d7005f'
yellow = '#00af5f'
blue = '#d78700'
magenta = '#0087d7'
cyan = '#d787d7'
white = '#00afaf'
black = "#000000"
red = "#d7005f"
green = "#00af5f"
yellow = "#d78700"
blue = "#0087d7"
magenta = "#d787d7"
cyan = "#00afaf"
white = "#dadada"

[colors.bright]
black = "#707070"
red = "#ff005f"
green = "#00d75f"
yellow = "#ffaf00"
blue = "#5fafff"
magenta = "#ff87ff"
cyan = "#00d7d7"
white = "#ffffff"
