inherits = "better_solarized_dark"

[palette]
red = '#dc322f'
green = '#859900'
yellow = '#b58900'
blue = '#268bd2'
magenta = '#d33682'
cyan = '#2aa198'
orange = '#cb4b16'
violet = '#6c71c4'

# 深色 越来越深
# dark getting darker
base0 = '#657b83'
base1 = '#586e75'
base2 = '#073642'
base3 = '#002b36'

# 浅色 越來越浅
# Lighter and lighter
base00 = '#839496'
base01 = '#93a1a1'
base015 = '#c5c8bd'
base0175 = '#dddbcc'
base02 = '#eee8d5'
base025 = '#f5eedb'
base03 = '#fdf6e3'
