"ui.cursor" = {bg="base05", fg="base00"}
"ui.selection" = {bg="#FFFFFF",fg="#000000"}
"string" = 'base0B'
"variable" = 'base08'
"constructor" = "base0A"
"comment" = "base03"
"ui.text" = "base05"
"operator" = "base05"
"keyword" = "base0E"
"function" = "base0D"
"type" = "base0A"

[palette]
base00= "#000000"
base01= "#121212"
base02= "#222222"
base03= "#333333"
base04= "#999999"
base05= "#c1c1c1"
base06= "#999999"
base07= "#c1c1c1"
base08= "#5f8787"
base09= "#aaaaaa"
base0A= "#a06666"
base0B= "#dd9999"
base0C= "#aaaaaa"
base0D= "#888888"
base0E= "#999999"
base0F= "#444444"
