inherits = "catppuccin_mocha"

"ui.background" = { fg = "text" }

"variable.builtin" = "maroon"
"variable.parameter" = "pink"
"keyword.control.conditional" = { fg = "mauve"}
"namespace" = { fg = "blue"}
"ui.bufferline.active" = { fg = "mauve", bg = "base"}

[palette]
base = "#1e1e1e"
mantle = "#282825"
crust = "#1e1e1e"
