inherits = "dracula"

[palette]
foreground = "#f8f8f2"
background = "#0B0D0F"
cursorline = "#2d303e"
darker = "#222430"
black = "#191A21"
grey = "#666771"
comment = "#708CA9"
current_line = "#44475a"
indent = "#56596a"
selection = "#414D58"
red = "#FF9580"
orange = "#FFCA80" 
yellow = "#FFFF80" 
green = "#8AFF80" 
purple = "#9580FF" 
cyan = "#80FFEA"
pink = "#FF80BF"

# Palette      | Hex       | RGB             | HSL             | ANSI 256
# ---          | ---       | ---             | ---             | ---
# Background   | `#0B0D0F` | `11, 13, 15`    | `210° 15% 15%`  | `16`
# Comment      | `#708CA9` | `112, 140, 169` | `210° 25% 55%`  | `109`
# Selection    | `#414D58` | `65, 77, 88`    | `210° 15% 30%`  | `66`

# """
# Palette      | Hex       | RGB             | HSL             | ANSI 256
# ---          | ---       | ---             | ---             | ---
# Foreground   | `#F8F8F2` | `248, 248, 242` | `60°  30% 96%`  | `231`
# Cyan         | `#80FFEA` | `128, 255, 234` | `170° 100% 75%` | `159`
# Green        | `#8AFF80` | `138, 255, 128` | `115° 100% 75%` | `157`
# Orange       | `#FFCA80` | `255, 202, 128` | `35°  100% 75%` | `223`
# Pink         | `#FF80BF` | `255, 128, 191` | `330° 100% 75%` | `218`
# Purple       | `#9580FF` | `149, 128, 255` | `250° 100% 75%` | `147`
# Red          | `#FF9580` | `255, 149, 128` | `10°  100% 75%` | `217`
# Yellow       | `#FFFF80` | `255, 255, 128` | `60°  100% 75%` | `229`
