inherits = "dracula"

[palette]
foreground        = "#F8F8F2"
background        = "#22212C"
cursorline        = "#2d303e"
darker            = "#222430"
black             = "#191A21"
grey              = "#666771"
comment           = "#7970a9"
current_line      = "#44475a"
indent            = "#56596a"
selection         = "#454158"
red               = "#FF9580"
orange            = "#FFCA80" 
yellow            = "#FFFF80" 
green             = "#8AFF80" 
purple            = "#9580FF" 
cyan              = "#80FFEA"
pink              = "#FF80BF"
