# Original theme: https://github.com/sainnhe/gruvbox-material

# Syntax Highlighting

# "attribute" = {}

"type" = "yellow"
# "type.builtin" = {}
# "type.parameter" = {}
# "type.enum" = {}
# "type.enum.variant" = {}

"constructor" = "green"

"constant" = "fg0"
"constant.builtin" = "purple"
"constant.builtin.boolean" = "purple"
# "constant.character" = ""
"constant.character.escape" = "aqua"
"constant.numeric" = "purple"
# "constant.numeric.integer" = {}
# "constant.numeric.float" = {}

"comment" = { fg = "grey1", modifiers = ["italic"] }
# "comment.line" = {}
# "comment.block" = {}
# "comment.block.documentation" = {}

"string" = "aqua"
# "string.regexp" = {}
# "string.special" = {}
"string.special.path" = "red"
# "string.special.url" = {}
"string.special.symbol" = "red"


"variable" = "fg1"
"variable.builtin" = "purple"
# "variable.parameter" = {}
"variable.other" = "aqua"
"variable.other.member" = "blue"

"label" = "blue"

"punctuation" = "fg2"
"punctuation.delimiter" = "grey2"
# "punctuation.bracket" = {}
"punctuation.special" = "yellow"

"keyword" = "red"
"keyword.control" = "red"
"keyword.control.conditional" = "red"
"keyword.control.repeat" = "red"
"keyword.control.import" = "red"
"keyword.control.return" = "red"
"keyword.control.exception" = "purple"
# "keyword.operator" = {}
# "keyword.directive" = {}
"keyword.function" = "red"
# "keyword.storage" = {}
# "keyword.storage.type" = {}
# "keyword.storage.modifier" = {}

"operator" = "orange"

"function" = "green"
"function.builtin" = "yellow"
# "function.method" = {}
# "function.macro" = {}
# "function.special" = {}

"tag" = "blue"
# "tag.builtin" = {}

"namespace" = "fg1"

# "special" = {}

# "markup" = {}
# "markup.heading" = {}
"markup.heading.marker" = "bg3"
"markup.heading.1" = "red"
"markup.heading.2" = "orange"
"markup.heading.3" = "yellow"
"markup.heading.4" = "green"
"markup.heading.5" = "aqua"
"markup.heading.6" = "blue"
"markup.list" = "blue"
# "markup.list.unnumbered" = {}
# "markup.list.numbered" = {}
# "markup.list.checked" = {}
# "markup.list.unchecked" = {}
"markup.bold" = {fg = "red", modifiers = ["bold"]}
"markup.italic" = {fg = "yellow", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = "blue"
# "markup.link.url" = { modifiers = ["underlined"] }
# "markup.link.label" = {}
# "markup.link.text" = "purple"
"markup.quote" = "green"
# "markup.raw" = "orange"
# "markup.raw.inline" = {}
# "markup.raw.block" = {}

# "diff" = {}
"diff.plus" = "bg_diff_green"
"diff.minus" = "bg_diff_red"
# "diff.minus.gutter" = {}
# "diff.plus.gutter" = {}
"diff.delta" = "bg_diff_blue"
# "diff.delta.moved" = {}
# "diff.delta.gutter" = {}

# Interface
# "markup.normal" = {}
# "markup.normal.completion" = {}
# "markup.normal.hover" = {}
# "markup.heading.completion" = {}
# "markup.heading.hover" = {}
# "markup.raw.completion" = {}
# "markup.raw.hover" = {}

# UI
"ui.background" = { bg = "bg0" }
# "ui.background.separator" = {}
"ui.cursor" = { bg = "fg0", fg = "bg_dim" }
"ui.cursor.normal" = { bg = "orange", fg = "bg_dim" }
"ui.cursor.insert" = { bg = "green", fg = "bg_dim" }
"ui.cursor.select" = { bg = "yellow", fg = "bg_dim" }
"ui.cursor.match" = { bg = "grey2", fg = "bg_dim" }
# "ui.cursor.primary" = {}
# "ui.cursor.primary.normal" = {}
# "ui.cursor.primary.insert" = {}
# "ui.cursor.primary.select" = {}
# "ui.debug.breakpoint" = {}
# "ui.debug.active" = {}
# "ui.gutter" = {}
# "ui.gutter.selected" = {}
# "ui.highlight.frameline" = {}
"ui.linenr" = "bg5"
"ui.linenr.selected" = "grey1"
"ui.statusline" = { fg = "fg1", bg = "bg_statusline1" }
"ui.statusline.inactive" = { fg = "fg0", bg = "bg_statusline2" }
"ui.statusline.normal" = { fg = "bg_dim", bg = "grey2", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg_dim", bg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg_dim", bg = "red", modifiers = ["bold"] }
# "ui.statusline.separator" = {}
"ui.bufferline" = { fg = "grey1", bg = "bg_dim" }
"ui.bufferline.active" = { fg = "fg1", bg = "bg0" }
# "ui.bufferline.background" = {}
"ui.popup" = { bg = "bg1" }
"ui.popup.info" = { bg = "bg1" }
"ui.window" = "bg1"
"ui.help" = { bg = "bg1", fg = "fg1" }
"ui.text" = "fg1"
"ui.text.focus" = "blue"
# "ui.text.inactive" = {}
"ui.text.info" = "fg1"
"ui.virtual.ruler" = { bg = "bg_statusline2" }
"ui.virtual.whitespace" = "fg1"
"ui.virtual.indent-guide" = "bg_statusline2"
# "ui.virtual.inlay-hint" = {}
# "ui.virtual.inlay-hint.parameter" = {}
# "ui.virtual.inlay-hint.type" = {}
# "ui.virtual.wrap" = {}
"ui.menu" = { fg = "fg1", bg = "bg_dim" }
"ui.menu.selected" = {fg = "red", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "fg1", bg = "bg5" }
"ui.selection" = { bg = "bg3" }
# "ui.selection.primary" = {}
# "ui.highlight" = {}
# "ui.cursorline.primary" = {}
# "ui.cursorline.secondary" = {}
# "ui.cursorcolumn.secondary" = {}

"warning" = "orange"
"error" = "red"
"info" = "blue"
"hint" = "purple"

# "diagnostic" = {}
"diagnostic.hint".underline = { color = "purple", style = "curl" }
"diagnostic.info".underline = { color = "blue", style = "curl" }
"diagnostic.warning".underline = { color = "orange", style = "curl" }
"diagnostic.error".underline = { color = "red", style = "curl" }

[palette]
bg_dim = "#1b1b1b"
bg0 = "#282828"
bg1 = "#32302f"
bg2 = "#32302f"
bg3 = "#45403d"
bg4 = "#45403d"
bg5 = "#5a524c"

bg_statusline1 = "#32302f"
bg_statusline2 = "#3a3735"
bg_statusline3 = "#504945"

bg_diff_green = "#34381b"
bg_diff_red = "#402120"
bg_diff_blue = "#0e363e"

bg_visual_green = "#374141"
bg_visual_red = "#4c3432"
bg_visual_blue = "#374141"
bg_visual_yellow = "#4f422e"

bg_red = "#ea6962"
bg_green = "#a9b665"
bg_yellow = "#d8a657"

bg_current_word = "#3c3836"

fg0 = "#d4be98"
fg1 = "#ddc7a1"

# Primary colors
red = "#ea6962"
orange = "#e78a4e"
yellow = "#d8a657"
green = "#a9b665"

# Secondary colors
aqua = "#89b482"
blue = "#7daea3"
purple = "#d3869b"

# Greys
grey0 = "#7c6f64"
grey1 = "#928374"
grey2 = "#a89984"
