# Original theme: https://github.com/sainnhe/gruvbox-material

inherits = "gruvbox_material_dark_medium"

[palette]
bg_dim = "#141617"
bg0 = "#1d2021"
bg1 = "#282828"
bg2 = "#282828"
bg3 = "#3c3836"
bg4 = "#3c3836"
bg5 = "#504945"

bg_statusline1 = "#282828"
bg_statusline2 = "#32302f"
bg_statusline3 = "#504945"

bg_diff_green = "#32361a"
bg_diff_red = "#3c1f1e"
bg_diff_blue = "#0d3138"

bg_visual_green = "#333e34"
bg_visual_red = "#442e2d"
bg_visual_blue = "#2e3b3b"
bg_visual_yellow = "#473c29"

bg_red = "#ea6962"
bg_green = "#a9b665"
bg_yellow = "#d8a657"

bg_current_word = "#32302f"

fg0 = "#d4be98"
fg1 = "#ddc7a1"

# Primary colors
red = "#ea6962"
orange = "#e78a4e"
yellow = "#d8a657"
green = "#a9b665"

# Secondary colors
aqua = "#89b482"
blue = "#7daea3"
purple = "#d3869b"

# Greys
grey0 = "#7c6f64"
grey1 = "#928374"
grey2 = "#a89984"
