inherits = "catppuccin_latte"

"type.builtin" = { fg = "yellow", modifiers = ["italic"] }
"function.builtion" = { fg = "blue", modifiers = ["italic"] }
"variable.builtin" = "maroon"
"variable.parameter" = "pink"
"keyword.control.conditional" = { fg = "mauve" }
"namespace" = { fg = "blue" }
"ui.bufferline.active" = { fg = "mauve", bg = "base" }
"keyword.storage.modifier" = { fg = "teal" }
