"type" = "olive"
"constructor" = "magenta"
"constant" = "cyan"
"comment" = { fg = "sky", modifiers = ["italic"] }
"string" = "green"
"variable" = "sun"
"variable.builtin" = "orange"
"punctuation" = "sky"
"keyword" = "purple"
"function" = "blue"
"namespace" = "sky+"

"markup.heading" = { fg = "sky+", modifiers = ["bold"] }
"markup.heading.marker" = "sky-"
"markup.heading.1" = "red"
"markup.heading.2" = "orange"
"markup.heading.3" = "olive"
"markup.heading.4" = "green"
"markup.heading.5" = "cyan"
"markup.heading.6" = "blue"
"markup.list" = "sky+"
"markup.list.checked" = "green"
"markup.list.unchecked" = "orange"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { modifiers = ["underlined"] }
"markup.link.text" = "purple"
"markup.quote" = "green"
"markup.raw" = "orange"

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "cyan"

"ui.background" = { bg = "shade" }
"ui.background.separator" = "sky"
"ui.cursor" = {bg="sun", fg="shade-" }
"ui.cursor.match" = { bg = "shade+" }
"ui.cursorline.primary" = { bg = "shade+" }
"ui.linenr" = "sky-"
"ui.linenr.selected" = "sky+"
"ui.statusline" = { fg = "sky", bg = "shade-" }
"ui.statusline.inactive" = { fg = "sky", bg = "shade+" }
"ui.statusline.normal" = { fg = "shade", bg = "blue", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "shade", bg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "shade", bg = "purple", modifiers = ["bold"] }
"ui.bufferline" = { fg = "sky-", bg = "shade-" }
"ui.bufferline.active" = { fg = "sun", bg = "shade" }
"ui.popup" = { bg = "shade-" }
"ui.popup.info" = { bg = "shade" }
"ui.window" = "sky"
"ui.text" = "sky+"
"ui.text.focus" = "blue"
"ui.text.info" = "sky+"
"ui.virtual.ruler" = { bg = "shade-" }
"ui.virtual.whitespace" = "sky-"
"ui.virtual.indent-guide" = "shade+"
"ui.menu" = { fg = "sky", bg = "shade-" }
"ui.menu.selected" = { fg = "blue", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "sky", bg = "shade+" }
"ui.selection" = { bg = "sky-"}

"warning" = "orange"
"error" = "red"
"info" = "blue"
"hint" = "purple"

"diagnostic.hint".underline = { color = "purple", style = "curl" }
"diagnostic.info".underline = { color = "blue", style = "curl" }
"diagnostic.warning".underline = { color = "orange", style = "curl" }
"diagnostic.error".underline = { color = "red", style = "curl" }

[palette]
red = "#F58C81"
orange = "#E09F47"
olive = "#A9B852"
green = "#54C794"
cyan = "#00C4D7"
blue = "#6EB2FD"
purple = "#B69CF6"
magenta = "#E58CC5"

# Base Colours
"sun+" = "#FFFDFB"
"sun" = "#FFF7ED"
"sun-" = "#F2E6D4"
"sky+" = "#DEDEDE"
"sky" = "#AEAEAE"
"sky-" = "#636363"
"shade+" = "#3E4044"
"shade" = "#181B1F"
"shade-" = "#0D0F13"

