inherits = "solarized_light"

"ui.statusline" = { fg = "base0", bg = "base02" }
"ui.statusline.normal" = { fg = "base03",bg = "blue" }
"ui.statusline.insert" = { fg = "base03",bg = "green" }
"ui.statusline.select" = { fg = "base03",bg = "yellow" }

"ui.statusline.active" = { fg = "magenta", bg = "base02" }
"ui.statusline.inactive" = { fg = "base1", bg = "base02" }
"ui.virtual.ruler" = { bg = "base02" }
"ui.linenr" = { fg = "base0", bg = "base03" }

"comment" = { fg = "base01", modifiers = ["italic"] }

"warning" =  { fg = "orange"}
"error" = { fg = "red"}
"info" = { fg = "blue"}
"hint" = { fg = "base01"}

# Markup
"markup.bold" = { fg = "blue", modifiers = ["bold"] }
"markup.italic" = { fg = "blue", modifiers = ["italic"] }
"markup.link.text" = "violet"
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.heading.1" = "yellow"
"markup.heading.2" = "green"
"markup.heading.3" = "violet"
"markup.heading.4" = "blue"
"markup.list" = "orange"

# "diagnostic.error" = { fg = "red", modifiers = ["bold"] }
# "diagnostic.warning" = { fg = "orange", modifiers = ["bold"] }
# "diagnostic.hint" = { fg = "base01", modifiers = ["bold"] }
# "diagnostic.info" = { fg = "blue", modifiers = ["bold"] }
