"type" =  "base09"
"type.builtin" = "base09"
# "type.parameter" = "red"
# "type.enum" = {}
# "type.enum.variant" = {}

"constructor" = "base09"

"constant" = "base09"
# "constant.builtin" = {}
"constant.builtin.boolean" = "base09"
# "constant.character" = "purple"
"constant.character.escape" = "base0F"
"constant.numeric" = "base0F"
# "constant.numeric.integer" = {}
# "constant.numeric.float" = {}

"comment" = { fg = "base03", modifiers = ["italic"] }
# "comment.line" = {}
# "comment.block" = {}
# "comment.block.documentation" = {}

"string" = "base0E"
# "string.regexp" = {}
# "string.special" = {}
"string.special.path" = "base08"
# "string.special.url" = {}
"string.special.symbol" = "base08"

"variable" = "base05"
# "variable.builtin" = "base09"
# "variable.parameter" = "base09"
"variable.other" = "base0A"
"variable.other.member" = "base0A"

"label" = "base09"

"punctuation" = "base08"
"punctuation.delimiter" = "base08"
# "punctuation.bracket" = {}
"punctuation.special" = "base09"

"keyword" = "base08"
# "keyword.control" = "base09"
"keyword.control.conditional" = { fg = "base09", modifiers = ["italic"] }
"keyword.control.repeat" = {fg = "base09"}
"keyword.control.import" = { fg = 'base09'}
"keyword.operator" = "base08"
"keyword.directive" = {}
"keyword.control.return" = { fg = 'purple', modifiers = ['italic'] }
"keyword.control.exception" = "cyan"
# "keyword.function" = "purple"
# "keyword.storage" = {}
# "keyword.storage.type" = {}
# "keyword.storage.modifier" = {}


"operator" = "base09"

"function" = {fg = "base0C", modifiers = ["bold"]}
"function.builtin" = {fg = "base09", modifiers = ["bold"]}
"function.method" = "base07"
# "function.macro" = "purple"
# "function.special" = {}

# "tag" = "blue"
# "tag.builtin" = {}

# "namespace" = "sky+"

# "special" = {}

"ui.background" = { bg = "base00" }
"ui.background.separator" = "sky"
"ui.cursor" = {bg="base06", fg="base00"}
# "ui.cursor.normal" = {bg="orange", fg="shade-" }
# "ui.cursor.insert" = {bg="orange", fg="shade-" }
# "ui.cursor.select" = {bg="orange", fg="shade-" }
"ui.cursor.match" = { bg = "shade+" }
# "ui.cursor.primary" = {bg = "shade-"}
# "ui.cursor.primary.normal" = {}
# "ui.cursor.primary.insert" = {}
# "ui.cursor.primary.select" = {}
# "ui.debug.breakpoint" = {}
# "ui.debug.active" = {}
# "ui.gutter" = {}
# "ui.gutter.selected" = {}
# "ui.highlight.frameline" = {}
"ui.linenr" = "base03"
"ui.linenr.selected" = "sky+"
"ui.statusline" = { fg = "base05", bg = "base01" }
"ui.statusline.inactive" = { fg = "sky", bg = "shade+" }
"ui.statusline.normal" = { fg = "base00", bg = "base09", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "base00", bg = "base0D", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "base00", bg = "base0E", modifiers = ["bold"] }
# "ui.statusline.separator" = {}
"ui.bufferline" = { fg = "base03", bg = "base01" }
"ui.bufferline.active" = { fg = "base06", bg = "base00" }
# "ui.bufferline.background" = {k
"ui.popup" = { bg = "shade-" }
"ui.popup.info" = { bg = "shade" }
"ui.window" = "sky"
# "ui.help" = {}
"ui.text" = "base05"
"ui.text.focus" = "blue"
# "ui.text.inactive" = {}
"ui.text.info" = "sky+"
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.whitespace" = "sky-"
"ui.virtual.indent-guide" = "base03"
# "ui.virtual.inlay-hint" = {}
# "ui.virtual.inlay-hint.parameter" = {}
# "ui.virtual.inlay-hint.type" = {}
# "ui.virtual.wrap" = {}
"ui.menu" = { fg = "sky", bg = "shade-" }
"ui.menu.selected" = { fg = "blue", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "sky", bg = "shade+" }
"ui.selection" = {bg= "base02"}
# "ui.selection.primary" = {}
# "ui.highlight" = {}
"ui.cursorline.primary" = { bg = "base01" }
# "ui.cursorline.secondary" = {}
# "ui.cursorcolumn.secondary" = {}

"warning" = "yellow"
"error" = "base0A"
"info" = "base09"
"hint" = "base0E"

"diagnostic.hint".underline = { color = "base0E", style = "curl" }
"diagnostic.info".underline = { color = "base09", style = "curl" }
"diagnostic.warning".underline = { color = "yellow", style = "curl" }
"diagnostic.error".underline = { color = "base0A", style = "curl" }



[palette]
base00 = "#161616" 
base01 = "#262626" 
base02 = "#393939" 
base03 = "#525252" 
base04 = "#dde1e6" 
base05 = "#f2f4f8" 
base06 = "#ffffff" # White
base07 = "#08bdba" # Dark cyan 
base08 = "#3ddbd9" # Light cyan
base09 = "#78a9ff" # Pale blue
base0A = "#ee5396" # Red
base0B = "#33b1ff" # Indigo blue
base0C = "#ff7eb6" # Pink
base0D = "#42be65" # Green
base0E = "#be95ff" # Purple
base0F = "#82cfff" # Baby blue

black = '#000000'
yellow = "#ffe97b"
