# General
"warning" = { fg = "yellow" }
"error" = { fg = "red" }
"info" = { fg = "blue" }
"hint" = { fg = "base01" }

# Ui
"ui.background" = { bg = "bg_0" }
"ui.window" = { fg = "bg_1" }
"ui.gutter" = {}

"ui.text" = { fg = "fg_1" }
"ui.text.focus" = { fg = "blue", modifiers = ["bold"] }
"ui.text.info" = { fg = "bg_2", modifiers = ["bold"] }

"ui.cursor" = { fg = "bg_0", bg = "cyan" }
"ui.cursor.primary" = { fg = "bg_0", bg = "fg_1" }
"ui.cursor.insert" = { fg = "bg_0", bg = "fg_0" }
"ui.cursor.select" = { fg = "br_blue", bg = "red" }
"ui.cursor.match" = { fg = "bg_0", bg = "br_yellow" }

"ui.cursorline" = { bg = "bg_1" }
"ui.cursorline.primary" = { bg = "bg_1" }
"ui.cursorline.secondary" = { bg = "bg_1" }

"ui.virtual.whitespace" = { fg = "base01" }
"ui.virtual.inlay-hint" = { fg = "base01", modifiers = ["italic"] }
"ui.virtual.ruler" = { bg = "base02" }
"ui.virtual.indent-guide" = { fg = "base02" }

"ui.linenr.selected" = { fg = "fg_1" }

"ui.statusline" = { fg = "fg_0", bg = "bg_1" }
"ui.statusline.normal" = { fg = "bg_0", bg = "blue" }
"ui.statusline.insert" = { fg = "bg_0", bg = "green" }
"ui.statusline.select" = { fg = "bg_0", bg = "yellow" }
"ui.statusline.active" = { fg = "br_blue", bg = "bg_1" }
"ui.statusline.inactive" = { fg = "dim_0", bg = "bg_1" }

"ui.linenr" = { fg = "dim_0", bg = "bg_0" }
"ui.popup" = { bg = "bg_2" }

"ui.menu.selected" = { fg = "bg_2", bg = "fg_1" }
"ui.menu" = { fg = "fg_1", bg = "bg_1" }

"ui.help" = { modifiers = ["reversed"] }

"ui.popup.info" = { fg = "bg_0", bg = "fg_1", modifiers = ["bold"] }

"ui.highlight" = { fg = "red", modifiers = ["bold", "italic", "underlined"] }

"ui.selection" = { bg = "bg_2" }
"ui.selection.primary" = { bg = "bg_2" }

# Syntax highlighting
"attribute" = { fg = "violet" }
"special" = { fg = "red" }
"property" = {}

"type" = { fg = "green" }
"type.builtin" = { fg = "yellow", modifiers = ["bold"] }
"type.enum.variant" = { fg = "yellow" }

"constructor" = { fg = "blue" }

"constant" = { fg = "cyan" }
"constant.builtin" = { fg = "cyan", modifiers = ["bold"] }
# "constant.builtin.boolean" = {}
# "constant.character" = {}
"constant.character.escape" = { fg = "orange", modifiers = ["bold"] }
# "constant.numeric" = {}
# "constant.numeric.integer" = {}
# "constant.numeric.float" = {}

"string" = { fg = "cyan" }
"string.regexp" = {}
"string.special" = {}
"string.special.path" = {}
"string.special.url" = {}
"string.special.symbol" = {}

"comment" = { fg = "dim_0", modifiers = ["italic"] }
"comment.line" = {}
"comment.block" = {}
"comment.block.documentation" = {}

"variable" = {}
"variable.builtin" = { fg = "cyan", modifiers = ["bold"] }
"variable.function" = { fg = "blue" }
"variable.other.member" = {}

"label" = { fg = "green" }

"punctuation" = {}
"punctuation.delimiter" = {}
"punctuation.bracket" = {}

"keyword" = { fg = "green" }
"keyword.control" = {}
"keyword.control.conditional" = {}
"keyword.control.repeat" = {}
"keyword.control.import" = {}
"keyword.control.return" = {}
"keyword.control.exception" = {}
"keyword.operator" = {}
"keyword.directive" = { fg = "orange" }
"keyword.function" = {}
"keyword.storage.modifier" = "violet"

"operator" = { fg = "br_yellow" }

"function" = { fg = "br_blue" }
"function.macro" = { fg = "magenta" }
"function.method" = {}
"function.builtin" = { fg = "blue", modifiers = ["bold"] }
"function.special" = { fg = "magenta" }

"tag" = {}
"tag.error" = {}

"namespace" = { fg = "violet" }

"module" = { fg = "violet" }

#Markup
"markup.heading.1" = "yellow"
"markup.heading.2" = "green"
"markup.heading.3" = "violet"
"markup.heading.4" = "blue"
"markup.heading.5" = {}
"markup.heading.6" = {}

"markup.list" = "orange"
"markup.list.numbered" = {}
"markup.list.unnumbered" = {}

"markup.bold" = { fg = "base2", modifiers = ["bold"] }
"markup.italic" = { fg = "base2", modifiers = ["italic"] }

"markup.link" = {}
"markup.link.label" = {}
"markup.link.text" = "violet"
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }

"markup.normal" = {}
"markup.normal.completion" = {}
"markup.normal.raw" = {}

"markup.heading.completion" = {}
"markup.heading.raw" = {}

"markup.raw" = "green"
"markup.raw.block" = {}
"markup.raw.inline" = {}
"markup.raw.inline.completion" = {}
"markup.raw.inline.hover" = {}

"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.quote" = "cyan"

# Diff
"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "red" }
"diff.delta.moved" = {}

"diagnostic.warning" = { underline = { style = "curl", color = "orange" } }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"diagnostic.info" = { underline = { style = "curl", color = "blue" } }
"diagnostic.hint" = { underline = { style = "curl", color = "base01" } }


[palette]
bg_0 = "#103c48"
bg_1 = "#184956"
bg_2 = "#2d5b69"
dim_0 = "#72898f"
fg_0 = "#adbcbc"
fg_1 = "#cad8d9"

red = "#fa5750"
green = "#75b938"
yellow = "#dbb32d"
blue = "#4695f7"
magenta = "#f275be"
cyan = "#41c7b9"
orange = "#ed8649"
violet = "#af88eb"

br_red = "#ff665c"
br_green = "#84c747"
br_yellow = "#ebc13d"
br_blue = "#58a3ff"
br_magenta = "#ff84cd"
br_cyan = "#53d6c7"
br_orange = "#fd9456"
br_violet = "#bd96fa"
