"ui.background" = { fg = "white"}
"ui.background.separator" = { fg = "gray" }
"ui.text" = { fg = "light-gray" }
"ui.text.focus" = { fg = "white" }
"ui.menu" = {bg="dark-gray", fg = "white" }
"ui.menu.selected" = {bg="selection", modifiers = ["bold"]}
"ui.menu.scroll" = { fg = "light-gray" }
"ui.linenr" = { fg = "red", modifiers = ["bold"] }
"ui.popup" = { fg = "white" }
"ui.window" = { fg = "gray" }
"ui.selection" = {bg = "selection" }
"comment" = {fg = "gray", modifiers = ['italic']}
"operator" = "light-gray"
"ui.bufferline.active" = {bg="black",fg="white"}
"ui.bufferline.inactive" = {bg="black", fg="gray"}
"ui.bufferline" = {bg="black"}
"ui.statusline" = { bg = "dark-gray", fg = "white"}
"ui.statusline.inactive" = { fg = "gray" }
"ui.statusline.normal" = { fg = "black", bg = "blue" }
"ui.statusline.insert" = { fg = "black", bg = "green" }
"ui.statusline.select" = { fg = "black", bg = "magenta" }
"ui.help" = { fg = "light-gray" }
"ui.cursor" = {bg = "cursor"}
"ui.cursor.match" = { fg = "light-yellow", underline = { color = "light-yellow", style = "line" } }
"ui.cursor.primary" = {bg = "#53ae71", fg = "black"}
"ui.cursor.secondary" = { modifiers = ["reversed"] }
"ui.virtual.ruler" = { bg = "dark-gray" }
"ui.virtual.whitespace" = "gray"
"ui.virtual.indent-guide" = "dark-gray"
"ui.virtual.inlay-hint" = { fg = "white", bg = "gray" }
"ui.virtual.inlay-hint.parameter" = { fg = "white", bg = "gray"}
"ui.virtual.inlay-hint.type" = { fg = "white", bg = "gray"}
"ui.virtual.wrap" = "gray"
"ui.cursorline.primary" = { bg = "dark-gray" }

"variable" = "white"
"constant.numeric" = "magenta"
"constant.builtin.boolean" = {fg = "cyan"}
"constant" = "light-blue"
"attribute" = "yellow"
"type" = "cyan"
"string"  = "magenta"
"constant.character.escape" = "red"
"function" = "cyan"
"constructor" = {fg = "cyan"}
"special" = "light-blue"
"keyword" = "light-yellow"
"keyword.control.import" = "light-blue"
"label" = "light-magenta"
"namespace" = "white"

"markup.heading" = "light-blue"
"markup.list" = "light-red"
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "light-magenta", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "yellow", underline = { color = "yellow", style = "line"} }
"markup.link.text" = "light-red"
"markup.quote" = "light-cyan"
"markup.raw" = "green"
"markup.normal" = { fg = "blue" }
"markup.insert" = { fg = "green" }
"markup.select" = { fg = "magenta" }

"diff.plus" = "light-green"
"diff.delta" = "light-blue"
"diff.delta.moved" = "blue"
"diff.minus" = "light-red"

"ui.gutter" = "gray"
"info" = "light-blue"
"hint" = "light-gray"
"debug" = "light-gray"
"warning" = "light-yellow"
"error" = "light-red"

"diagnostic.info" = { underline = { color = "light-blue", style = "dotted" } }
"diagnostic.hint" = { underline = { color = "light-gray", style = "double_line" } }
"diagnostic.debug" = { underline ={ color ="light-gray", style = "dashed" } }
"diagnostic.warning" = { underline = { color = "light-yellow", style = "curl" } }
"diagnostic.error" = { underline = { color ="light-red", style = "curl" } }


[palette]
selection = "#4c3c54"
dark-gray = "#1b1b1b"
cursor = "#53ae71"
