theme = "catppuccin_custom"

[editor]
auto-pairs = true
auto-save = true
true-color = true
shell = ["fish", "-c"]
line-number = "relative"
bufferline = 'always'
mouse = true
color-modes = true
cursorline = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""
wrap-at-text-width = true

[editor.lsp]
# display-messages = true
display-inlay-hints = true
auto-signature-help = true
display-signature-help-docs = false


[editor.statusline]
left = ["mode", "spinner"]
center = ["version-control"]
right = [
  "diagnostics",
  "primary-selection-length",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.indent-guides]
render = true

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
C-r = ":reload"
C-p = ['move_line_up', "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-h = ["delete_selection", "move_char_left", "paste_before"]
A-l = ["delete_selection", "move_char_right", "paste_after"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
C-g = ["suspend"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"

[keys.normal.space]
y = ":primary-clipboard-yank"
