theme = "catppuccin_americano_transparent"
# theme = "catppuccin_americano_markdown"

[editor]
auto-save = true
true-color = true
shell = ["fish", "-c"]
line-number = "relative"
bufferline = 'always'
mouse = true
# text-width = 120
color-modes = true
cursorline = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 25             # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""       # set wrap-indicator to "" to hide it
wrap-at-text-width = true

[editor.lsp]
display-inlay-hints = true
auto-signature-help = true
display-signature-help-docs = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["version-control"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.indent-guides]
render = true

[keys.normal]
C-r = ":reload"
C-p = ['move_line_up', "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

C-f = [":new", ":insert-output lf-pick", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":theme nord", ":theme catppuccin_americano_transparent"] # replace the default after theme with the theme you use
# open 1 with the open command (l and <left> to open) or more with (<space> to select) then quit
# all opened files will be opened in helix


[keys.normal.space]
# l = ":toggle lsp.display-inlay-hints"
# q = ":toggle lsp.auto-signature-help"
