theme = "night"

[editor]
auto-save = true
true-color = true
shell = ["fish", "-c"]
line-number = "relative"
bufferline = 'always'
mouse = true
color-modes = true
cursorline = true
idle-timeout = 0


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""
wrap-at-text-width = true

[editor.lsp]
display-inlay-hints = true
auto-signature-help = true
display-signature-help-docs = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["version-control"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.indent-guides]
render = true

[keys.normal]
C-r = ":reload"
C-p = ['move_line_up', "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
