theme = "custom"

[editor]
auto-save = true
true-color = true
shell = ["fish", "-c"]
line-number = "relative"
bufferline = 'always'
mouse = true
color-modes = true
cursorline = true
idle-timeout = 0


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""
wrap-at-text-width = true

[editor.lsp]
display-inlay-hints = true
auto-signature-help = true
display-signature-help-docs = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["version-control"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.indent-guides]
render = true

[keys.normal]
C-r = ":reload"
C-p = ['move_line_up', "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

[keys.normal."'"]
"." = "repeat_last_motion"
"`" = "switch_to_uppercase"
"d" = "delete_selection_noyank"
"c" = "change_selection_noyank"
"C" = "copy_selection_on_prev_line"
"s" = "split_selection_on_newline"
"minus" = "merge_selections"
"_" = "merge_consecutive_selections"
";" = "flip_selections"
"e" = "move_parent_node_end"
"b" = "move_parent_node_start"
"x" = "shrink_to_line_bounds"
"u" = "earlier"
"U" = "later"
"J" = "join_selections_space"
"K" = "remove_selections"
"," = "remove_primary_selection"
"(" = "rotate_selection_contents_backward"
")" = "rotate_selection_contents_forward"
":" = "ensure_selections_forward"
"|" = "shell_pipe_to"
"!" = "shell_append_output"

"o" = "expand_selection"
"up" = "expand_selection"
"i" = "shrink_selection"
"down" = "shrink_selection"
"p" = "select_prev_sibling"
"right" = "select_next_sibling"
"n" = "select_next_sibling"
"left" = "select_prev_sibling"
