theme = "catppuccin_mocha"

[editor]
true-color = true
shell = ['fish']
line-number = "relative"
bufferline = 'always'
mouse = true
text-width = 80
color-modes = true
cursorline = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 25             # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""       # set wrap-indicator to "" to hide it
wrap-at-text-width = true

[editor.lsp]
display-inlay-hints = true
auto-signature-help = true
display-signature-help-docs = false

# [editor.statusline]
# left = ["mode", "file-name"]
# center = ['spinner']
# right = [
#   "diagnostics",
#   "version-control",
#   "position-percentage",
#   "file-encoding",
#   "file-line-ending",
#   "file-type",
# ]

[editor.indent-guides]
render = true

[keys.normal]
# Use system clipboard
# y = "yank_main_selection_to_clipboard"
# p = "paste_clipboard_before"
C-p = ['move_line_up', "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

[keys.normal.space]
# l = ":toggle lsp.display-inlay-hints"
# q = ":toggle lsp.auto-signature-help"
