[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", ".pythonstartup", ".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright", "ruff", "pylsp"]
indent = { tab-width = 4, unit = "    " }
auto-format = true
rulers = [80]


[language.formatter]
command = "bash"
args = ["-c", "isort - | black - --line-length=79"]


[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config]
settings = { args = [] }

[[language]]
name = "toml"
scope = "source.toml"
injection-regex = "toml"
file-types = ["toml"]
language-servers = ["taplo"]
auto-format = true

[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]
auto-format = true
text-width = 300

[language.formatter]
command = "dotnet"
args = ["csharpier"]

[language-server.omnisharp]
command = "dotnet"
args = [
  "/Users/nshern/Downloads/omnisharp-osx-arm64-net6.0/OmniSharp.dll",
  "--languageserver",
]

[[language]]
name = "markdown"
scope = "source.markdown"
text-width = 200
injection-regex = "markdown"
file-types = ["md"]
language-servers = ["mdpls", "marksman", "ltex-ls"]
formatter = { command = "prettier" }
auto-format = true

[language-server.mdpls]
name = "markdown"
command = "mdpls"
config = { markdown.preview.auto = false, markdown.preview.browser = "firefox" }


[language-server.marksman]
name = "markdown"
command = "marksman"

[language-server.ltex-ls]
name = "markdown"
command = "ltex-ls"
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []
config = { ltex.disabledRules = { "en-US" = [
  "PROFANITY",
], "en-GB" = [
  "PROFANITY",
] }, ltex.dictionary = { "en-US" = [
  "madeupword",
  "watchamacallit",
], "en-GB" = [
  "madeupword",
], "da-DK" = [
  "GDPR",
] } }
