# Python
[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright", "ruff"]
formatter = { command = "black" , args = ["-", "--quiet", "--line-length=88"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.pyright]
command = "pyright"

# [language.formatter]
# command = "black"
# args = [
#   "-",
#   "--quiet",
#   "--line-length=88"
# ]

# [language-server.pyright]
# command = "pyright-langserver"
# args = ["--stdio"]

# [language-server.pyright.config]
# reportMissingTypeStubs = false

# [language-server.pyright.config.python.analysis]
# typeCheckingMode = "basic"
# autoImportCompletions = true


# [language-server.ruff.config]
# settings = {args = []}

#TOML
[[language]]
name = "toml"
scope = "source.toml"
injection-regex = "toml"
file-types = ["toml"]
formatter = { command = "prettier" }
language-servers = ["taplo"]
auto-format = true


# Markdown
[[language]]
name = "markdown"
scope = "source.markdown"
injection-regex = "markdown"
file-types = ["md"]
language-servers = ["ltex-ls" ,"marksman"]

[language-server.marksman]
command = "marksman"

[language-server.ltex-ls]
name = "markdown"
command = "ltex-ls"
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []
config = { ltex.disabledRules = { "en-US" = [
  "PROFANITY",
], "en-GB" = [
  "PROFANITY",
] }, ltex.dictionary = { "en-US" = [
  "madeupword",
  "watchamacallit",
], "en-GB" = [
  "madeupword",
] } }
