[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
# language-servers = ["pylsp", "pyright", "ruff"]
language-servers = ["pylsp", "ruff", "pyright"]
indent = { tab-width = 4, unit = "    " }
auto-format = true
rulers = [80]

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=79"
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config]
settings = {args = []}

#TOML
[[language]]
name = "toml"
scope = "source.toml"
injection-regex = "toml"
file-types = ["toml"]
formatter = { command = "prettier" }
language-servers = ["taplo"]
auto-format = true

[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]
auto-format = true

[language-server.omnisharp]
command = "dotnet"
args = [
  "/Users/nshern/Downloads/omnisharp-osx-arm64-net6.0/OmniSharp.dll",
  "--languageserver"
  ]


# Markdown
[[language]]
name = "markdown"
scope = "source.markdown"
text-width = 300
injection-regex = "markdown"
file-types = ["md"]
language-servers = ["ltex-ls" ,"marksman"]
formatter = {command = "prettier"}
auto-format = true

[language-server.marksman]
command = "marksman"

[language-server.ltex-ls]
name = "markdown"
command = "ltex-ls"
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []
config = { ltex.disabledRules = { "en-US" = [
  "PROFANITY",
], "en-GB" = [
  "PROFANITY",
] }, ltex.dictionary = { "en-US" = [
  "madeupword",
  "watchamacallit",
], "en-GB" = [
  "madeupword",
] } }
