# [[language]]
# name = "python"
# # language-server = { command = "ruff-lsp" }

# # In case you'd like to use ruff alongside black for code formatting:
# formatter = { command = "black", args = ["--quiet", "-"] }
# auto-format = true

[[language]]
text-width = 120
name = "python"
config = { pylsp = { plugins = { pycodestyle = { enabled = false }, flake8 = { enabled = true, maxLineLength = 120 }, pyflakes = { enabled = false } } } }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
[[language]]
name = "rust"

[language.config.check]
command = "clippy"


[[language]]
name = "svelte"
formatter = { command = "prettier" }
auto-format = true


[[language]]
name = "typescript"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true
config = {}


[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = 'fish'
formatter = { command = "prettier" }
auto-format = true


[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "Dockerfile.lambda"]
auto-format = true

[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []
config = { ltex.disabledRules = { "en-US" = [
  "PROFANITY",
], "en-GB" = [
  "PROFANITY",
] }, ltex.dictionary = { "en-US" = [
  "madeupword",
  "watchamacallit",
], "en-GB" = [
  "madeupword",
] } }

# [[language]]
# name = "markdown"
# language-server = { command = "marksman"}
# file-types = ["md", "txt"]
# scope = "source.markdown"
# roots = []
