format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$line_break\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[Î»](cyan)"
error_symbol = "[X](red)"
vimcmd_symbol = "[V](green)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[python]
format = "[$virtualenv]($style)"
style = "bright-black"
