format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$line_break\
$character"""

[directory]
style = "blue"

[character]
# success_symbol = "[ζ](purple)"
# error_symbol = "[ζ](red)"
# vimcmd_symbol = "[ζ](green)"

success_symbol = "[ζ](purple)"
error_symbol = "[ξ](red)"
vimcmd_symbol = "[Ξ](green)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[python]
format = "[$virtualenv]($style)"
style = "bright-black"


