# Wez
[colors]
foreground = '#14161b'
background = '#e0e2ea'
cursor_bg = "#53ae71"
cursor_border = "#53ae71"
cursor_fg = "#000000"
selection_bg = "#4d52f8"
selection_fg = "#000000"

ansi = [
  "#000000",
  "#cc5555",
  "#55cc55",
  "#cdcd55",
  "#5555cc",
  "#cc55cc",
  "#7acaca",
  "#cccccc",
]
brights = [

  "#000000",
  "#cc5555",
  "#55cc55",
  "#cdcd55",
  "#5555cc",
  "#cc55cc",
  "#7acaca",
  "#cccccc",
]

[metadata]
aliases = []
name = 'bar'
