[colors]
ansi = [
  "#000000",
  "#121212",
  "#222222",
  "#333333",
  "#999999",
  "#c1c1c1",
  "#999999",
  "#c1c1c1",
]
background = '#000000'
brights = [
  "5f8787",
  "aaaaaa",
  "a06666",
  "dd9999",
  "aaaaaa",
  "888888",
  "999999",
  "444444",
]
cursor_bg = '#c1c1c1'
cursor_border = '#c1c1c1'

# cursor_fg = '#141617' # fg_dim
# foreground = '#d4be98' # fg0
# selection_bg = '#3c3836' # bg3/bg4
# selection_fg = '#141617' # fg_dim


# [colors.indexed]

# [colors.tab_bar]
# background = '#24272b'

# [colors.tab_bar.active_tab]
# bg_color = '#303338'
# fg_color = '#bebebe'
# intensity = 'Normal'
# italic = false
# strikethrough = false
# underline = 'None'

# [colors.tab_bar.inactive_tab]
# bg_color = '#24272b'
# fg_color = '#636363'
# intensity = 'Normal'
# italic = false
# strikethrough = false
# underline = 'None'

# [colors.tab_bar.new_tab]
# bg_color = '#24272b'
# fg_color = '#636363'
# intensity = 'Normal'
# italic = false
# strikethrough = false
# underline = 'None'

[metadata]
name = 'black_metal'
