[colors]
foreground = "#e0e0e0"
background = "#262626"
cursor_fg = "#262626"
cursor_bg = "#e0e0e0"
cursor_border = "#262626"
selection_bg = "#0043ce"

ansi = [
	"#262626",
	"#ffb3b8",
	"#6fdc8c",
	"#f1c21b",
	"#82cfff",
	"#d4bbff",
	"#3ddbd9",
	"#e0e0e0",
]
brights = [
	"#6f6f6f",
	"#ffb3b8",
	"#6fdc8c",
	"#f1c21b",
	"#82cfff",
	"#d4bbff",
	"#3ddbd9",
	"#ffffff",
]

[colors.tab_bar]
background = '#262626'
inactive_tab_edge = '#262626'

[colors.tab_bar.active_tab]
fg_color = '#262626'
bg_color = '#e0e0e0'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#262626'
fg_color = '#C4C6CD'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e0e0e0'
fg_color = '#262626'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#262626'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#262626'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'carbonized_dark'
