
[colors]
background = "#ffffff"
foreground = "#161616"
cursor_fg = "#ffffff"
cursor_bg = "#161616"
cursor_border = "#ffffff"
selection_bg = "#a6c8ff"

ansi = [
	"#ffffff",
	"#a2191f",
	"#0e6027",
	"#684e00",
	"#00539a",
	"#6929c4",
	"#005d5d",
	"#161616",
]
brights = [
	"#525252",
	"#a2191f",
	"#0e6027",
	"#684e00",
	"#00539a",
	"#6929c4",
	"#005d5d",
	"#161616",
]

[colors.tab_bar]
background = '#ffffff'
inactive_tab_edge = '#ffffff'

[colors.tab_bar.active_tab]
fg_color = '#ffffff'
bg_color = '#161616'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ffffff'
fg_color = '#4f5258'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#161616'
fg_color = '#C4c6cd'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#ffffff'
fg_color = '#4f5258'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#ffffff'
fg_color = '#4f5258'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'carbonized_light'
