[colors]
ansi = [
    '#3b224c',
    '#f47868',
    '#9ff28f',
    '#efba5d',
    '#a4a0e8',
    '#dbbfef',
    '#6acdca',
    '#ebeafa',
]
background = '#3b224c'
brights = [
    '#697c81',
    '#ff3334',
    '#9ec400',
    '#e7c547',
    '#7aa6da',
    '#b77ee0',
    '#54ced6',
    '#ffffff',

]
cursor_bg = '#9a9a9a'
cursor_border = '9a9a9a'
cursor_fg = '#ffffff'
foreground = '#ebeafa'
selection_bg = '#540099'

[colors.indexed]

[colors.tab_bar]
background = '#24272b'

[colors.tab_bar.active_tab]
bg_color = '#303338'
fg_color = '#bebebe'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#24272b'
fg_color = '#636363'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#24272b'
fg_color = '#636363'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'colibri'
