[colors]
foreground = "#b3b3b3"
background = "#000000"
cursor_bg = "#53ae71"
cursor_border = "#53ae71"
cursor_fg = "#000000"
selection_bg = "#4c3c54"
# selection_fg = "#000000"

ansi = ["#000000","#cc5555","#55cc55","#cdcd55","#5555cc","#cc55cc","#7acaca","#cccccc"]
brights = ["#555555","#ff5555","#55ff55","#ffff55","#5555ff","#ff55ff","#55ffff","#ffffff"]

[colors.indexed]

[colors.tab_bar]
background = "#000000"

[colors.tab_bar.active_tab]
bg_color = '#000000'
fg_color = '#FFFFFF'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#000000'
fg_color = '#555555'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#000000'
fg_color = '#555555'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'



[metadata]
name = 'custom'


