
# foreground = "#ffffff",
# background = "#16181a",
#
# cursor_bg = "#ffffff",
# cursor_fg = "#000000",
# cursor_border = "#ffffff",
#
# selection_fg = "#ffffff",
# selection_bg = "#3c4048",
#
# scrollbar_thumb = "#16181a",
# split = "#16181a",
#
# ansi = { "#16181a", "#ff6e5e", "#5eff6c", "#f1ff5e", "#5ea1ff", "#bd5eff", "#5ef1ff", "#ffffff" },
# brights = { "#3c4048", "#ff6e5e", "#5eff6c", "#f1ff5e", "#5ea1ff", "#bd5eff", "#5ef1ff", "#ffffff" },
# indexed = { [16] = "#ffbd5e", [17] = "#ff6e5e" },
[colors]
ansi = [
  "#16181a",
  "#ff6e5e",
  "#5eff6c",
  "#f1ff5e",
  "#5ea1ff",
  "#bd5eff",
  "#5ef1ff",
  "#ffffff",
]
background = '#16181a'
brights = [
  "#3c4048",
  "#ff6e5e",
  "#5eff6c",
  "#f1ff5e",
  "#5ea1ff",
  "#bd5eff",
  "#5ef1ff",
  "#ffffff",
]
foreground = "#ffffff"
cursor_bg = "#ffffff"
cursor_fg = "#000000"
cursor_border = "#ffffff"

selection_fg = "#ffffff"
selection_bg = "#3c4048"

scrollbar_thumb = "#16181a"
split = "#16181a"

[colors.indexed]
16 = '#ffbd5e'
17 = '#ff6e5e'

[colors.tab_bar]
background = '#161616'
inactive_tab_edge = '#161616'

[colors.tab_bar.active_tab]
fg_color = '#94e2d5'
bg_color = '#161616'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#161616'
fg_color = '#7f849c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#161616'
fg_color = '#7f849c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#161616'
fg_color = '#7f849c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#45475a'
fg_color = '#cdd6f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'Cyberdream'
