    # background = "#181818",
    # darkest = "#1e1e1e",
    # darker = "#292929",
    # dark = "#898989",
    #
    # light = "#d6d6dd",
    # lightest = "#ffffff",
    #
    # dark_gray = "#535353",
    # light_gray = "#6d6d6d",
    # purple = "#a390f0",
    # light_blue = "#7dbeff",
    # blue = "#52a7f6",
    # pink = "#d898d8",
    # green = "#afcb85",
    # cyan = "#78d0bd",
    # orange = "#efb080",
    # yellow = "#e5c995",
    # red = "#CC7C8A",
    #
    # blue_accent = "#2197F3",
    # pink_accent = "#E44C7A",
    # green_accent = "#00AF99",
    # orange_accent = "#EE7F25",
    # yellow_accent = "#DEA407",
    # red_accent = "#F44747",
    #
    # red_error = "#EB5F6A",
    # selection = "#1F3661",
    # diff_plus = "#5A9F81",
    # focus = "#204474",
    #
    # error_bg = "#4d2a2c",
    # warning_bg = "#4e321b",
    # info_bg = "#484849",
    # hint_bg = "#263c50",

[colors]
foreground = "#d6d6dd"
background = "#181818"
cursor_fg = "#181818"
cursor_bg = "#d6d6dd"
cursor_border = "#181818"
selection_bg = "#1F3661"

ansi = [
	"#1e1e1e",
	"#cc7c8a",
	"#afcb85",
	"#e5c995",
	"#52a7f6",
	"#d898d8",
	"#78d0bd",
	"#d6d6dd",
]
brights = [
	"#898989",
	"#cc7c8a",
	"#afcb85",
	"#e5c995",
	"#52a7f6",
	"#d898d8",
	"#78d0bd",
	"#ffffff",
]

[colors.tab_bar]
background = '#181818'
inactive_tab_edge = '#181818'

[colors.tab_bar.active_tab]
fg_color = '#181818'
bg_color = '#d6d6dd'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#181818'
fg_color = '#C4C6CD'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#d6d6dd'
fg_color = '#181818'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#181818'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#181818'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'fleet'
