[colors]
foreground = "#d4be98"
background = "#1d2021"
cursor_fg = "#1d2021"
cursor_bg = "#d4be98"
cursor_border = "#1d2021"
selection_bg = "#3c3836"

ansi = [
    "#504945",
    "#ea6962",
    "#a9b665",
    "#d8a657",
    "#7daea3",
    "#d3869b",
    "#89b482",
    "#d4be98",
]
brights = [

    "#504945",
    "#ea6962",
    "#a9b665",
    "#d8a657",
    "#7daea3",
    "#d3869b",
    "#89b482",
    "#d4be98",
]

[colors.tab_bar]
background = '#1d2021'
inactive_tab_edge = '#1d2021'

[colors.tab_bar.active_tab]
fg_color = '#1d2021'
bg_color = '#d4be98'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1d2021'
fg_color = '#C4C6CD'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#d4be98'
fg_color = '#1d2021'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#1d2021'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#1d2021'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'gruvbox_material_dark'
