[colors]
ansi = [
  '#3C3836',
  '#EA6962',
  '#A9B665',
  '#D8A657',
  '#7DAEA3',
  '#D3869B',
  '#89B482',
  '#D4BE98',
]
background = '#1d2021'      # bg0
brights = [
  '#3C3836',
  '#EA6962',
  '#A9B665',
  '#D8A657',
  '#7DAEA3',
  '#D3869B',
  '#89B482',
  '#D4BE98',
]
cursor_bg = '#d4be98'        # fg0
cursor_border = '#d4be98'    # fg0
cursor_fg = '#141617'        # fg_dim
foreground = '#d4be98'       # fg0
selection_bg = '#3c3836'     # bg3/bg4
selection_fg = '#141617'     # fg_dim


[colors.indexed]

[colors.tab_bar]
background = '#24272b'

[colors.tab_bar.active_tab]
bg_color = '#303338'
fg_color = '#bebebe'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#24272b'
fg_color = '#636363'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#24272b'
fg_color = '#636363'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'gruvbox_material_dark_hard'
