[colors]
background = "#ffffff"
foreground = "#000000"
cursor_fg = "#ffffff"
cursor_bg = "#000000"
cursor_border = "#ffffff"
selection_bg = "#193668"

ansi = [
	"#f2f2f2",
	"#a60000",
	"#006800",
	"#6f5500",
	"#0031a9",
	"#721045",
	"#005e8b",
	"#000000",
]
brights = [
	"#9f9f9f",
	"#a60000",
	"#006800",
	"#6f5500",
	"#0031a9",
	"#721045",
	"#005e8b",
	"#595959",
]

[colors.tab_bar]
background = '#ffffff'
inactive_tab_edge = '#ffffff'

[colors.tab_bar.active_tab]
fg_color = '#ffffff'
bg_color = '#000000'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ffffff'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ffffff'
fg_color = '#000000'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#ffffff'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#ffffff'
fg_color = '#000000'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'hush light'
