[colors]
foreground = "#d0d0d0"
background = "#0a2a2a"
cursor_fg = "#0a2a2a"
cursor_bg = "#d0d0d0"
cursor_border = "#0a2a2a"
selection_bg = "#4f5258"

# base00 = '#0a2a2a',
# base01 = '#324747',
# base02 = '#556868',
# base03 = '#788a8a',
# base04 = '#bbbbbb',
# base05 = '#d0d0d0',
# base06 = '#e6e6e6',
# base07 = '#fcfcfc',
#
# base08 = '#ebcd91',
# base09 = '#9f8340',
# base0A = '#209870',
# base0B = '#82e3ba',
# base0C = '#bb6d9b',
# base0D = '#a9d4ff',
# base0E = '#ffb9e5',
# base0F = '#598ab9',

ansi = [
	"#324747",
	"#ffb9e5",
	"#82e3ba",
	"#ebcd91",
	"#598ab9",
	"#bb5d9b",
	"#a9d4ff",
	"#e6e6e6",
]
brights = [
	"#556868",
	"#ffb9e5",
	"#82e3ba",
	"#ebcd91",
	"#598ab9",
	"#bb5d9b",
	"#a9d4ff",
	"#d0d0d0",
]

[colors.tab_bar]
background = '#0a2a2a'
inactive_tab_edge = '#0a2a2a'

[colors.tab_bar.active_tab]
fg_color = '#0a2a2a'
bg_color = '#fcfcfc'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#0a2a2a'
fg_color = '#C4C6CD'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#fcfcfc'
fg_color = '#0a2a2a'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#0a2a2a'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#0a2a2a'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'minicyan dark'
