[colors]
background = "#ffffff"
foreground = "#000000"
cursor_fg = "#ffffff"
cursor_bg = "#000000"
cursor_border = "#ffffff"
selection_bg = "#a6c8ff"

ansi = [
    "#ffffff",
    "#750e13",
    "#0e6027",
    "#684e00",
    "#00539a",
    "#6929c4",
    "#005d5d",
    "#000000",
]
brights = [
    "#525252",
    "#750e13",
    "#0e6027",
    "#684e00",
    "#00539a",
    "#6929c4",
    "#005d5d",
    "#000000",
]

[colors.tab_bar]
background = '#ffffff'
inactive_tab_edge = '#ffffff'

[colors.tab_bar.active_tab]
fg_color = '#ffffff'
bg_color = '#000000'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ffffff'
fg_color = '#4f5258'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#000000'
fg_color = '#C4c6cd'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#ffffff'
fg_color = '#4f5258'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#ffffff'
fg_color = '#4f5258'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'minicarbon_light'
