[colors]
foreground = "#d0d0d0"
background = "#000000"
cursor_fg = "#000000"
cursor_bg = "#d0d0d0"
cursor_border = "#000000"
selection_bg = "#0087d7"

ansi = [
    "#000000",
    "#d7005f",
    "#00af5f",
    "#d78700",
    "#0087d7",
    "#d787d7",
    "#00afaf",
    "#d0d0d0",
]
brights = [
    "#767676",
    "#ff5f87",
    "#00d75f",
    "#ffaf00",
    "#00afff",
    "#ff87ff",
    "#00d7d7",
    "#ffffff",
]

[colors.tab_bar]
background = '#000000'
inactive_tab_edge = '#000000'

[colors.tab_bar.active_tab]
fg_color = '#000000'
bg_color = '#d0d0d0'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#000000'
fg_color = '#C4C6CD'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#d0d0d0'
fg_color = '#000000'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#000000'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#000000'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'minicharm_dark'
