# NvimLightBlue: #a6dbff
# NvimLightCyan: #8cf8f7
# NvimLightGreen: #b3f6c0
# NvimLightGrey1: #eef1f8
# NvimLightGrey2: #e0e2ea
# NvimLightGrey3: #c4c6cd
# NvimLightGrey4: #9b9ea4
# NvimLightMagenta: #ffcaff
# NvimLightRed: #ffc0b9
# NvimLightYellow: #fce094
# NvimDarkGrey1: #07080d
# NvimDarkGrey2: #14161b
# NvimDarkGrey3: #2c2e33

[colors]
ansi = [
  '#14161b',
  '#ffc0b9',
  '#b3f6c0',
  '#fce094',
  '#a6dbff',
  '#ffcaff',
  '#8cf8f7',
  '#c4c6cd',
]
background = '#14161b'
brights = [
  '#9b9ea4',
  '#ffc0b9',
  '#b3f6c0',
  '#fce094',
  '#a6dbff',
  '#ffcaff',
  '#8cf8f7',
  '#9b9ea4',
]

compose_cursor = '#8cf8f7'
cursor_bg = '#8cf8f7'
cursor_border = '#8cf8f7'
cursor_fg = '#07080d'
foreground = '#eef1f8'
scrollbar_thumb = '#9b9ea4'
selection_bg = '#9b9ea4'
selection_fg = '#4c4f69'
split = '#9b9ea4'
visual_bell = '#c4c6cd'

[colors.indexed]
16 = '#fe640b'
17 = '#dc8a78'

[colors.tab_bar]
background = '#14161b'
inactive_tab_edge = '#ccd0da'

[colors.tab_bar.active_tab]
bg_color = '#8cf8f7'
fg_color = '#07080d'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#14161b'
fg_color = '#e0e2ea'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eff1f5'
fg_color = '#4c4f69'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#ccd0da'
fg_color = '#4f5258'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#bcc0cc'
fg_color = '#4c4f69'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'nvim dark'
