
[colors]
ansi = [
  '#c4c6cd',
  '#590008',
  '#004423',
  '#6b5300',
  '#004c73',
  '#470045',
  '#007373',
  '#14161b',
]
background = '#e0e2ea'
brights = [
  '#9b9ea4',
  '#590008',
  '#004423',
  '#6b5300',
  '#004c73',
  '#470045',
  '#007373',
  '#2c2e33',
]

compose_cursor = '#004c73'
cursor_bg = '#004c73'
cursor_border = '#004c73'
cursor_fg = '#e0e2ea'
foreground = '#14161b'
scrollbar_thumb = '#9b9ea4'
selection_bg = '#9b9ea4'
selection_fg = '#4c4f69'
split = '#9b9ea4'
visual_bell = '#c4c6cd'

[colors.indexed]
16 = '#fe640b'
17 = '#dc8a78'

[colors.tab_bar]
background = '#dce0e8'
inactive_tab_edge = '#ccd0da'

[colors.tab_bar.active_tab]
bg_color = '#007373'
fg_color = '#e0e2ea'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e0e2ea'
fg_color = '#4c4f69'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eff1f5'
fg_color = '#4c4f69'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#ccd0da'
fg_color = '#4f5258'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#bcc0cc'
fg_color = '#4c4f69'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'nvim light'
