
[colors]
background = "#24272b"
foreground = "#cecece"
cursor_fg = "#24272b"
cursor_bg = "#cecece"
cursor_border = "#24272b"
selection_bg = "#3e4044"


ansi = [
	"#181b1f",
	"#ca736c",
	"#47a477",
	"#8d9741",
	"#5794d0",
	"#bc73a4",
	"#00a2af",
	"#fffdfb",
]
brights = [
	"#636363",
	"#ca736c",
	"#47a477",
	"#8d9741",
	"#5794d0",
	"#bc73a4",
	"#00a2af",
	"#cecece",
]

[colors.tab_bar]
background = '#24272b'
inactive_tab_edge = '#24272b'

[colors.tab_bar.active_tab]
bg_color = '#636363'
fg_color = '#cecece'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#24272b'
fg_color = '#cecece'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#636363'
fg_color = '#cecece'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#24272b'
fg_color = '#cecece'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#636363'
fg_color = '#cecece'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'penumbra dark+'
