
[colors]
background = "#303338"
foreground = "#bebebe"
cursor_fg = "#303338"
cursor_bg = "#bebebe"
cursor_border = "#303338"
selection_bg = "#3e4044"


ansi = [
	"#24272b",
	"#ca736c",
	"#47a477",
	"#8d9741",
	"#5794d0",
	"#bc73a4",
	"#00a2af",
	"#fffdfb",
]
brights = [
	"#636363",
	"#ca736c",
	"#47a477",
	"#8d9741",
	"#5794d0",
	"#bc73a4",
	"#00a2af",
	"#bebebe",
]

[colors.tab_bar]
background = '#303338'
inactive_tab_edge = '#303338'

[colors.tab_bar.active_tab]
bg_color = '#636363'
fg_color = '#bebebe'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#303338'
fg_color = '#bebebe'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#636363'
fg_color = '#bebebe'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#303338'
fg_color = '#bebebe'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#636363'
fg_color = '#bebebe'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'penumbra dark'
