
# base00 = '#fff7ed', -- Lighter Background (Used for status bars, line number and folding marks)
# base01 = '#fff7ed', -- Default Background
# base02 = '#bebebe', -- Selection Background
# base03 = '#8f8f8f', -- Comments, Invisibles, Line Highlighting
# base04 = '#636363', -- Dark Foreground (Used for status bars)
# base05 = '#3e4044', -- Default Foreground, Caret, Delimiters, Operators
# base06 = '#303338', -- Light Foreground (Not often used)
# base07 = '#24272b', -- Light Background (Not often used)
# base08 = '#CA736C', -- Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
# base09 = '#BA823A', -- Integers, Boolean, Constants, XML Attributes, Markup Link Url
# base0A = '#8D9741', -- Classes, Markup Bold, Search Text Background
# base0B = '#47A477', -- Strings, Inherited Class, Markup Code, Diff Inserted
# base0C = '#00A2AF', -- Support, Regular Expressions, Escape Characters, Markup Quotes
# base0D = '#5794D0', -- Functions, Methods, Attribute IDs, Headings
# base0E = '#9481CC', -- Keywords, Storage, Selector, Markup Italic, Diff Changed
# base0F = '#BC73A4', -- Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>

[colors]
background = "#fff7ed"
foreground = "#3e4044"
cursor_fg = "#fff7ed"
cursor_bg = "#3e4044"
cursor_border = "#fff7ed"
selection_bg = "#8f8f8f"

ansi = [
	"#636363",
	"#ca736c",
	"#47a477",
	"#8d9741",
	"#5794d0",
	"#bc73a4",
	"#00a2af",
	"#24272b",
]
brights = [
	"#8f8f8f",
	"#ca736c",
	"#47a477",
	"#8d9741",
	"#5794d0",
	"#bc73a4",
	"#00a2af",
	"#3e4044",
]

[colors.tab_bar]
background = '#fff7ed'
inactive_tab_edge = '#fff7ed'

[colors.tab_bar.active_tab]
bg_color = '#8f8f8f'
fg_color = '#3e4044'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#fff7ed'
fg_color = '#3e4044'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#3e4044'
fg_color = '#C4c6cd'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#fff7ed'
fg_color = '#3e4044'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e4044'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'penumbra light'
