[colors]
ansi = [
  '#000000',
  '#af0000',
  '#005f00',
  '#af5f00',
  '#005faf',
  '#870087',
  '#008787',
  '#d7d7d7',
]

brights = [
  '#626262',
  '#d70000',
  '#008700',
  '#d78700',
  '#0087d7',
  '#af00af',
  '#00afaf',
  '#ffffff',
]

background = "#d7d7d7"
foreground = "#000000"
cursor_bg = "#53ae71"
cursor_border = "#53ae71"
cursor_fg = "#000000"
selection_bg = "#4d52f8"
selection_fg = "#000000"

[metadata]
aliases = []
name = 'quietus light'
