[colors]
foreground = "#839496"
background = "#002b36"
cursor_fg = "#002b36"
cursor_bg = "#839496"
cursor_border = "#002b36"
selection_bg = "#eee8d5"

ansi = [
	"#002b36",
	"#dc322f",
	"#859900",
	"#b58900",
	"#268bd2",
	"#d33682",
	"#2aa198",
	"#eee8d5",
]
brights = [
	"#073642",
	"#dc322f",
	"#859900",
	"#b58900",
	"#268bd2",
	"#d33682",
	"#2aa198",
	"#fdf6e3",
]

[colors.tab_bar]
background = '#002b36'
inactive_tab_edge = '#002b36'

[colors.tab_bar.active_tab]
fg_color = '#002b36'
bg_color = '#839496'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#002b36'
fg_color = '#C4C6CD'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#839496'
fg_color = '#002b36'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#002b36'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#002b36'
fg_color = '#c4c6cd'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'foo'
