[colors]
foreground = "#353535"
background = "#EEEEEE"
cursor_fg = "#EEEEEE"
cursor_bg = "#353535"
cursor_border = "#EEEEEE"
# selection_fg = "#353535"
selection_bg = "#D7D7D7"

ansi = [
  "#EEEEEE",
  "#A8334C",
  "#4F6C31",
  "#944927",
  "#286486",
  "#88507D",
  "#3B8992",
  "#353535",
]
brights = [
  "#C6C3C3",
  "#94253E",
  "#3F5A22",
  "#803D1C",
  "#1D5573",
  "#7B3B70",
  "#2B747C",
  "#5C5C5C",
]

[colors.tab_bar]
background = '#EEEEEE'
inactive_tab_edge = '#EEEEEE'

[colors.tab_bar.active_tab]
fg_color = '#EEEEEE'
bg_color = '#3B8992'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#EEEEEE'
fg_color = '#353535'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#3B8992'
fg_color = '#EEEEEE'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#EEEEEE'
fg_color = '#353535'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#EEEEEE'
fg_color = '#353535'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'zenwritten light'
