[colors]
foreground = "#BBBBBB"
background = "#191919"
cursor_fg = "#191919"
cursor_bg = "#C9C9C9"
cursor_border = "#191919"
selection_fg = "#BBBBBB"
selection_bg = "#404040"
ansi = [
	"#191919",
	"#DE6E7C",
	"#819B69",
	"#B77E64",
	"#6099C0",
	"#B279A7",
	"#66A5AD",
	"#BBBBBB",
]
brights = [
	"#3D3839",
	"#E8838F",
	"#8BAE68",
	"#D68C67",
	"#61ABDA",
	"#CF86C1",
	"#65B8C1",
	"#8E8E8E",
]

[colors.tab_bar]
background = '#191919'
inactive_tab_edge = '#191919'

[colors.tab_bar.active_tab]
fg_color = '#191919'
bg_color = '#BBBBBB'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#191919'
fg_color = '#BBBBBB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#BBBBBB'
fg_color = '#191919'
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#191919'
fg_color = '#BBBBBB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#191919'
fg_color = '#BBBBBB'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
name = 'zenwritten dark'
